# Generated by Django 3.1.7 on 2021-04-03 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_dealhand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealhand',
            name='cards_left',
        ),
        migrations.RemoveField(
            model_name='dealhand',
            name='reset',
        ),
    ]
