# Generated by Django 3.1.7 on 2021-04-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20210404_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeck',
            old_name='card',
            new_name='cards',
        ),
    ]
