# Generated by Django 3.1.7 on 2021-04-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20210404_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeck',
            old_name='cards',
            new_name='card',
        ),
    ]
