# Generated by Django 3.1.7 on 2021-04-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20210408_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeck',
        ),
    ]
