# Generated by Django 3.1.7 on 2021-04-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_delete_userdeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
