# Generated by Django 3.1.7 on 2021-04-09 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0013_remove_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('suit', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
