# Generated by Django 3.1.7 on 2021-04-09 04:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0014_testcard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCard',
            new_name='UserCard',
        ),
    ]
