# Generated by Django 3.1.7 on 2021-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('suit', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Battle',
        ),
    ]
