# Generated by Django 3.1.7 on 2021-03-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20210302_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
